name: Release Changelog

on:
  push:
    branches:
      - 'rel_*'
      - 'dev_1.x_tagged_services'

  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Generate AI changelog
        uses: d3datadevelopment/ci-actions/ai-changelog@dev-1.x-autochangelog
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          repo_url: https://git.d3data.de/DanielS/OxLogIQ
          push_token: ${{ secrets.GITEA_PUSH_TOKEN }}